- name : cerate ec2 and r53
  hosts: local
  connection: local
  vars:
    ami_id: "ami-09c813fb71547fc4f"
    sg_id: "sg-03d319dbe8210fee5" # replace with your SG ID
    zone_id: "Z05209902SM780XEQXZA1" # replace with your ID
    domain_name : "manisha.sbs"
  instances:
  - mongodb
  tasks:
  - name : "{{ item }}"
    amazon.aws.ec2_instance:
    instance_type: {{ t3.micro }}
    security_group: {{ sg_id }}
    image_id: {{ ami-id }}
    tags:
      Name: "{{ item }}"
    loop: {{ instances }}
    register: ec2_output


  - name : print the ec2 o/p
    debug:
      msg : "{{ ec2_output }}"

  