- name : setup catalogue server
  hosts: catalogue
  become: yes
  tasks:
  - name: disable nodejs 
    ansible.builtin.command:
      dnf module disable nodejs -y

  - name: enable nodejs 
    ansible.builtin.command:
      dnf module enable nodejs:20 -y

  - name: Install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: create roboshop system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      comment: roboshop system user
      system: true  #itla pedithe it makes the user as system account
      create_home: yes

  # - name: remove the directory first
  #   ansible.builtin.file:
  #     path: /app
  #     state: absent

  - name: Create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: remove the catalogue file
    ansible.builtin.file:
      path: /tmp/catalogue.zip
      state: absent

  - name: Download tthe catalogue applicaton
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
      dest: /tmp/catalogue.zip
  
  - name: Unarchive catalogue applicaton
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes
  
  # #akadikelli pakages anni install chesestadi depending on package.json
  # - name: install dependencies
  #   community.general.npm:
  #     path: /app

  

