- name : setup redis server
  hosts: rabbitmq
  become: yes
  tasks:
  - name: copy rabbitmq repo
    ansible.builtin.copy:
      src: rabbitmq.repo
      dest: /etc/yum.repos.d/rabbitmq.repo

  - name : install rabbitmq-server server
    package:
      name: rabbitmq-server
      state: present
  - name: start  and enable  rabbitmq service
    ansible.builtin.service:
      name: rabbitmq-server
      state: started
      enabled: yes
  - name: create user for the application
    community.rabbitmq.rabbitmq_user:
      user: roboshop 
      password: roboshop123
      permissions:
        - vhost: /
          configure_priv: .*
          read_priv: .*
          write_priv: .*
      state: present